- include: del.yml
  vars:
    user: "{{ userid }}"
    t1name: "{{ userid }}_l1_target"
    h1name: "{{ userid }}_l1_host"
    t2name: "{{ userid }}_l2_target"
    h2name: "{{ userid }}_l2_host"
    wettyhost: "{{ userid }}_wetty"
