- at: command="curl -F \'name={{ userid }}\' \"http://192.168.0.154/cgi-bin/delete.cgi?\" >& /dev/null" state="absent"

- include: del.yml
  with_items:
    - "{{ t1name }}"
    - "{{ h1name }}"
    - "{{ t2name }}"
    - "{{ h2name }}"
    - "{{ sh1name }}"
    - "{{ st1name }}"
    - "{{ wettyhost }}"
  
