- include: users.yml
  vars:
    user: "{{ userid }}"
    port: "{{ blog }}"
    htty: "{{ htty }}"
    ttty: "{{ ttty }}"

- at: command="curl -F 'name={{ userid }}' 'http://{{ hostaddr }}/cgi-bin/delete.cgi?' >& /dev/null" count="{{ count }}" units="minutes"
