- block:
    - name: Boot Windows Server Instance from snapshot
      os_server:
        state: present
        auth:
          auth_url: "{{ url }}"
          username: "{{ myuser }}"
          password: "{{ mypass }}"
          project_name: "{{ tenant }}"
        name: "tis-{{ user }}-winsrv"
        image: "{{ image_win }}"
        timeout: 200
        flavor: "{{ flavor_win }}"
        security_groups: "{{ secg_all }}"
        nics:
          - net-id: "{{ net_id }}"
        auto_ip: yes
      tags: boot-win

#    - name: Destroy Windows Server Instance
#      os_server:
#        state: absent
#        auth:
#          auth_url: "{{ url }}"
#          username: "{{ myuser }}"
#          password: "{{ mypass }}"
#          project_name: "{{ tenant }}"
#        name: "tis-{{ user }}-winsrv"
#        image: "{{ image_win }}"
#      tags: delete-win
